version: '3.8'

services:
  frontend:
    build: ./src                          # Path to frontend Dockerfile
    ports:
      - "3000:80"                         # Maps frontend port to localhost:3000
    depends_on:
      - backend                           # Waits for backend service to start

  backend:
    build: ./api                          # Path to backend Dockerfile
    ports:
      - "5000:5000"                       # Maps backend port to localhost:5000